apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    app: vote
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000
      name:  "vote-service"
  selector:
    app: vote